feat: blog2/main
sern-handler/docs pull request #30
Opened 2022-12-15 16:37 UTC by jacoobes

adds the blog for 2.0 release and updates typedoc

2022-12-15 17:32 UTC, SrIzan10 commented
LOOK MOM IM FAMOUS

2022-12-15 17:40 UTC, SrIzan10 requested changes
```
<img src="https://img.srizan.ml/Discord_z8Sn1UBfEe.png" />
All deprecation warnings from previous versions have taken effect, and are removed in 2.0.
```
should be
```
<img src="https://img.srizan.ml/Discord_z8Sn1UBfEe.png" />

All deprecation warnings from previous versions have taken effect, and are removed in 2.0.
```

2022-12-15 17:49 UTC, SrIzan10 approved these changes

2022-12-28 19:41 UTC, Murtatrxx approved these changes

2022-12-28 19:41 UTC, Murtatrxx commented on blog/2022-12-13-mdx-blog-post.md
> -i should have eaten something before i feel hungry
🤨

2022-12-28 19:43 UTC, Murtatrxx commented
I'll fix all small things later, but it can be merged.

2022-12-28 19:43 UTC, merged