Add category files, fix some capitalization, and add new blog post
sern-handler/docs pull request #54
Opened 2024-02-23 13:05 UTC by DuroCodes

Adds the blog post about deploying Sern bot with Railway.
I also changed the docusaurus.config.js file so all blog posts display instead of only 5.
Updated some capitalization in titles, such as "transition from v2 to v3" → "Transition from v2 to v3"

2024-02-23 17:14 UTC, jacoobes commented
The sidebar seems to be not working 🤔 
![ảnh](https://github.com/sern-handler/website/assets/76754747/d3f4aa7f-8473-4e3a-aa74-964200b36220)
It doesn't expand to its subcontents

2024-02-23 17:46 UTC, SrIzan10 requested changes
there ya go, take a look at these :wink:

2024-02-23 17:46 UTC, SrIzan10 commented on blog/2024-02-23-mdx-blog-post.md
> +title: Deploying Sern with Railway
lowercase please (applies to all other lines with the same mistake)

2024-02-23 17:46 UTC, SrIzan10 commented on docusaurus.config.js
looks like you changed this file, please also edit `docgen.docusaurus.config.js`.

2024-02-29 14:44 UTC, SrIzan10 commented
I think it's ready to merge, but I want @Murtatrxx or @jacoobes' to have the last word

2024-02-29 14:47 UTC, Murtatrxx commented
Aren't these already planned for the guide update

2024-02-29 15:56 UTC, jacoobes commented
the tutorial pr has been stale for a while but i feel like this would be a nice addon. plus i think Duro is working on adding images

2024-03-15 16:09 UTC, jacoobes commented
ship it

2024-03-15 16:09 UTC, merged