starlight rewrite
sern-handler/docs pull request #64
Opened 2024-05-06 21:22 UTC by DuroCodes

rewrites the website from docusaurus -> starlight, please check thoroughly for any issues 🙏

2024-05-06 21:33 UTC, jacoobes commented
remove .DS_Store

2024-05-06 21:34 UTC, jacoobes commented
`git rm --cached src/**/*.DS_Store` i think, recommit and push

2024-05-06 21:39 UTC, jacoobes requested changes

2024-05-06 21:39 UTC, jacoobes commented on netlify.toml
need this to deploy

2024-05-06 21:39 UTC, jacoobes commented on .github/workflows/docusaurus.yml
need this as well to deploy. will need to switch it to deploy the astro starlight project

2024-05-06 21:39 UTC, jacoobes commented on 404.html
does astro have a default 404?

2024-05-06 21:47 UTC, jacoobes commented on .github/workflows/docusaurus.yml
i think its because the netlify preview not working so yea

2024-05-06 21:47 UTC, jacoobes commented on .github/workflows/docusaurus.yml
idk 100% tho

2024-05-07 01:07 UTC, DuroCodes commented on 404.html
yeah:
![image](https://github.com/sern-handler/website/assets/47304910/eb9beff3-78e9-45ef-bee6-16361f3cb00f)

2024-05-07 05:40 UTC, SrIzan10 commented on .github/workflows/github-pages.yml
> +  push:
friendly reminder for myself to add the `branches: [main]` rule when merging

2024-05-07 14:11 UTC, SrIzan10 commented
Are we ready to merge? I think I'm sending the @sernbot command

2024-05-07 14:12 UTC, jacoobes commented
I will need to double check once more

Vào Th 3, 7 thg 5, 2024 lúc 9:11 SA sernbot ***@***.***> đã
viết:

> Hey @SrIzan10 <https://github.com/SrIzan10>! I only need one more
> approval by the dev team before I can merge this PR.
> Just run the command approve merge.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sern-handler/website/pull/64#issuecomment-2098505511>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASJS6OY3RLULGW3OWZ27B3LZBDOJLAVCNFSM6AAAAABHJY4HTGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOJYGUYDKNJRGE>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-05-07 14:12 UTC, merged

2024-05-07 14:13 UTC, SrIzan10 commented
what the hell

2024-05-07 14:13 UTC, SrIzan10 commented
wait no fucking way