starlight rewrite 2
sern-handler/docs pull request #66
Opened 2024-05-07 15:41 UTC by DuroCodes

electric boogaloo

2024-05-07 16:01 UTC, SrIzan10 commented
we need a checklist

2024-05-07 20:53 UTC, jacoobes requested changes

2024-05-07 20:53 UTC, jacoobes commented on astro.config.mjs
> +
```suggestion
const BASE_LINK = "https://github.com/sern-handler"
```

2024-05-07 20:53 UTC, jacoobes commented on astro.config.mjs
> +			github: 'https://github.com/sern-handler',
```suggestion
			github: BASE_LINK,
```

2024-05-07 20:53 UTC, jacoobes commented on astro.config.mjs
> +			baseUrl: 'https://github.com/sern-handler/website/edit/main/',
```suggestion
			baseUrl: BASE_LINK+'/website/edit/main/',
```

2024-05-07 20:53 UTC, jacoobes commented on astro.config.mjs
> +			Head: './src/overrides/Head.astro',
do this for all the links

2024-05-08 15:28 UTC, SrIzan10 commented on src/components/SponsorCard.astro
I think that I got GPT to generate some type for that

2024-05-08 17:37 UTC, DuroCodes commented on src/components/SponsorCard.astro
added those types to `utils/types.ts` :fire:

2024-07-18 21:06 UTC, merged